export const Dishes = [
  {
    id: 1,
    origin: 'Spain',
    name: 'Spanish Paella',
    description:
      'Spanish paella is a traditional rice dish that originated in the Valencia region of Spain. It was originally made with ingredients such as saffron, rabbit, and snails, which were common in the area.',
    difficulty: 'Medium',
    seafood: 'Jumbo Shrimp',
    spices: ['Bay Leaf', 'Saffron'],
    volume: 700,
    authenticity: 'Unverified',
    produce: ['Onion', 'Tomatoes'],
    oliveoil: 'Spanish Olive Oil',
    serves: 4,
    stock: 'Chicken',
  },
  {
    id: 2,
    origin: 'Mexico',
    name: 'Tacos',
    description:
      'Tacos are a traditional Mexican dish consisting of a corn or wheat tortilla filled with a variety of meats, vegetables, and sauces. They are a popular street food in Mexico and have become increasingly popular in other parts of the world.',
    difficulty: 'Low',
    seafood: 'Lobster',
    spices: ['Chili Powder', 'Paprika'],
    volume: 400,
    authenticity: 'Mexican',
    produce: ['Lettuce', 'Radishes'],
    oliveoil: 'None',
    serves: 4,
    stock: 'Chicken',
  },

  {
    id: 3,
    origin: 'Japan',
    name: 'Sushi',
    description:
      'Sushi is a Japanese dish of vinegared rice combined with other ingredients, such as seafood, vegetables, and sometimes tropical fruits. It is often served with wasabi, pickled ginger, and soy sauce.',
    difficulty: 'High',
    seafood: 'Tuna',
    spices: ['Wasabi', 'Ginger'],
    volume: 800,
    authenticity: 'Japanese',
    produce: ['Rice', 'Avocado'],
    oliveoil: 'None',
    serves: 4,
    stock: 'None',
  },
]
